language: java
jdk:
  - oraclejdk7
  - openjdk7
branches:
  only:
    - master
    - atmosphere-2.2.x
    - atmosphere-2.3.x
    - atmosphere-2.4.x
before_install: 'mvn -version'
install: 'mvn clean install'
